build-kyria:
  cd /Users/reid/Documents/repos/qmk_firmware/keyboards/splitkb/kyria; qmk compile -kb splitkb/kyria/rev3 -km ReidMason

flash-kyria:
  cd /Users/reid/Documents/repos/qmk_firmware/keyboards/splitkb/kyria; qmk flash -kb splitkb/kyria/rev3 -km ReidMason
